/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TarifStufe = IDL.Record({
  'id' : IDL.Text,
  'preis' : IDL.Float64,
  'farbe' : IDL.Text,
});
export const TarifPeriode = IDL.Record({
  'id' : IDL.Text,
  'bis' : IDL.Text,
  'von' : IDL.Text,
  'stufen' : IDL.Vec(TarifStufe),
  'owner' : IDL.Principal,
  'einspeiseStufen' : IDL.Vec(TarifStufe),
  'zuordnungBezug' : IDL.Vec(IDL.Vec(IDL.Text)),
  'bezugStufen' : IDL.Vec(TarifStufe),
  'zuordnungEinspeisung' : IDL.Vec(IDL.Vec(IDL.Text)),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'co2Faktor' : IDL.Float64,
  'registeredAt' : Time,
  'waehrung' : IDL.Text,
  'pvName' : IDL.Text,
});
export const AnalyticsResult = IDL.Record({
  'id' : IDL.Text,
  'selfConsumptionRate' : IDL.Float64,
  'totalEVCharging' : IDL.Float64,
  'autarkyRate' : IDL.Float64,
  'totalGridFeedIn' : IDL.Float64,
  'owner' : IDL.Principal,
  'totalGridDraw' : IDL.Float64,
  'totalPVGeneration' : IDL.Float64,
  'pvShareOfEVCharging' : IDL.Float64,
  'timestamp' : Time,
});
export const PVSession = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'data' : IDL.Text,
  'name' : IDL.Text,
  'timestamp' : Time,
});
export const PremiumSession = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'data' : IDL.Text,
  'name' : IDL.Text,
  'timestamp' : Time,
});
export const WattpilotSession = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'data' : IDL.Text,
  'name' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPVSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addPremiumSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addTarifPeriode' : IDL.Func([TarifPeriode], [], []),
  'addWattpilotSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'appendPremiumSessionData' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteTarifPeriode' : IDL.Func([IDL.Text], [], []),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLatestAnalyticsResult' : IDL.Func(
      [],
      [IDL.Opt(AnalyticsResult)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getPVSampleData' : IDL.Func([], [IDL.Text], ['query']),
  'getPVSessions' : IDL.Func([], [IDL.Vec(PVSession)], ['query']),
  'getPremiumSessions' : IDL.Func([], [IDL.Vec(PremiumSession)], ['query']),
  'getSession' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], ['query']),
  'getTarifPerioden' : IDL.Func([], [IDL.Vec(TarifPeriode)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWattpilotSampleData' : IDL.Func([], [IDL.Text], ['query']),
  'getWattpilotSessions' : IDL.Func([], [IDL.Vec(WattpilotSession)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'saveAnalyticsResult' : IDL.Func([IDL.Text, AnalyticsResult], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCo2Faktor' : IDL.Func([IDL.Float64], [], []),
  'updateTarifPeriode' : IDL.Func([TarifPeriode], [], []),
  'updateWaehrung' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TarifStufe = IDL.Record({
    'id' : IDL.Text,
    'preis' : IDL.Float64,
    'farbe' : IDL.Text,
  });
  const TarifPeriode = IDL.Record({
    'id' : IDL.Text,
    'bis' : IDL.Text,
    'von' : IDL.Text,
    'stufen' : IDL.Vec(TarifStufe),
    'owner' : IDL.Principal,
    'einspeiseStufen' : IDL.Vec(TarifStufe),
    'zuordnungBezug' : IDL.Vec(IDL.Vec(IDL.Text)),
    'bezugStufen' : IDL.Vec(TarifStufe),
    'zuordnungEinspeisung' : IDL.Vec(IDL.Vec(IDL.Text)),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'co2Faktor' : IDL.Float64,
    'registeredAt' : Time,
    'waehrung' : IDL.Text,
    'pvName' : IDL.Text,
  });
  const AnalyticsResult = IDL.Record({
    'id' : IDL.Text,
    'selfConsumptionRate' : IDL.Float64,
    'totalEVCharging' : IDL.Float64,
    'autarkyRate' : IDL.Float64,
    'totalGridFeedIn' : IDL.Float64,
    'owner' : IDL.Principal,
    'totalGridDraw' : IDL.Float64,
    'totalPVGeneration' : IDL.Float64,
    'pvShareOfEVCharging' : IDL.Float64,
    'timestamp' : Time,
  });
  const PVSession = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'data' : IDL.Text,
    'name' : IDL.Text,
    'timestamp' : Time,
  });
  const PremiumSession = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'data' : IDL.Text,
    'name' : IDL.Text,
    'timestamp' : Time,
  });
  const WattpilotSession = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'data' : IDL.Text,
    'name' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPVSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addPremiumSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addTarifPeriode' : IDL.Func([TarifPeriode], [], []),
    'addWattpilotSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'appendPremiumSessionData' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteTarifPeriode' : IDL.Func([IDL.Text], [], []),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLatestAnalyticsResult' : IDL.Func(
        [],
        [IDL.Opt(AnalyticsResult)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getPVSampleData' : IDL.Func([], [IDL.Text], ['query']),
    'getPVSessions' : IDL.Func([], [IDL.Vec(PVSession)], ['query']),
    'getPremiumSessions' : IDL.Func([], [IDL.Vec(PremiumSession)], ['query']),
    'getSession' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], ['query']),
    'getTarifPerioden' : IDL.Func([], [IDL.Vec(TarifPeriode)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWattpilotSampleData' : IDL.Func([], [IDL.Text], ['query']),
    'getWattpilotSessions' : IDL.Func(
        [],
        [IDL.Vec(WattpilotSession)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'saveAnalyticsResult' : IDL.Func([IDL.Text, AnalyticsResult], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCo2Faktor' : IDL.Func([IDL.Float64], [], []),
    'updateTarifPeriode' : IDL.Func([TarifPeriode], [], []),
    'updateWaehrung' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };