/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsResult {
  'id' : string,
  'selfConsumptionRate' : number,
  'totalEVCharging' : number,
  'autarkyRate' : number,
  'totalGridFeedIn' : number,
  'owner' : Principal,
  'totalGridDraw' : number,
  'totalPVGeneration' : number,
  'pvShareOfEVCharging' : number,
  'timestamp' : Time,
}
export interface PVSession {
  'id' : string,
  'owner' : Principal,
  'data' : string,
  'name' : string,
  'timestamp' : Time,
}
export interface PremiumSession {
  'id' : string,
  'owner' : Principal,
  'data' : string,
  'name' : string,
  'timestamp' : Time,
}
export interface TarifPeriode {
  'id' : string,
  'bis' : string,
  'von' : string,
  'stufen' : Array<TarifStufe>,
  'owner' : Principal,
  'einspeiseStufen' : Array<TarifStufe>,
  'zuordnungBezug' : Array<Array<string>>,
  'bezugStufen' : Array<TarifStufe>,
  'zuordnungEinspeisung' : Array<Array<string>>,
}
export interface TarifStufe {
  'id' : string,
  'preis' : number,
  'farbe' : string,
}
export type Time = bigint;
export interface UserProfile {
  'principal' : Principal,
  'co2Faktor' : number,
  'registeredAt' : Time,
  'waehrung' : string,
  'pvName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WattpilotSession {
  'id' : string,
  'owner' : Principal,
  'data' : string,
  'name' : string,
  'timestamp' : Time,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPVSession' : ActorMethod<[string, string, string], undefined>,
  'addPremiumSession' : ActorMethod<[string, string, string], undefined>,
  'addTarifPeriode' : ActorMethod<[TarifPeriode], undefined>,
  'addWattpilotSession' : ActorMethod<[string, string, string], undefined>,
  'appendPremiumSessionData' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteSession' : ActorMethod<[string, string], undefined>,
  'deleteTarifPeriode' : ActorMethod<[string], undefined>,
  'getAllProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLatestAnalyticsResult' : ActorMethod<[], [] | [AnalyticsResult]>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getPVSampleData' : ActorMethod<[], string>,
  'getPVSessions' : ActorMethod<[], Array<PVSession>>,
  'getPremiumSessions' : ActorMethod<[], Array<PremiumSession>>,
  'getSession' : ActorMethod<[string, string], string>,
  'getTarifPerioden' : ActorMethod<[], Array<TarifPeriode>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWattpilotSampleData' : ActorMethod<[], string>,
  'getWattpilotSessions' : ActorMethod<[], Array<WattpilotSession>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRegistered' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string], undefined>,
  'saveAnalyticsResult' : ActorMethod<[string, AnalyticsResult], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCo2Faktor' : ActorMethod<[number], undefined>,
  'updateTarifPeriode' : ActorMethod<[TarifPeriode], undefined>,
  'updateWaehrung' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];